#!/bin/sh

read -p "Install Brew?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "  Installing Brew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "  Installing Cask..."
  brew tap homebrew/cask
else
  echo "  Skip Brew Install"
fi

# Terminal
brew install tmux
brew install iTerm2

# Kakoune text editor
brew install kakoune

