# Show line numbers on left
hook global WinCreate .* %{addhl number_lines -hlcursor -separator '|'}
set-face LineNumberCursor white,black

# Hide clippy
set global ui_options ncurses_assistant=none

# Add scrolling bounds
set global scrolloff 9,5

# Set tab width
set-option global tabstop 4 

# Show whitespace characters
hook global WinCreate .* %{addhl show_whitespaces}
set-face Whitespace black+d

### ##### #####
set-face PrimaryCursor yellow+r

# This should add surround functionality (pressing ,s<surround with char>)
def surround %!on-key %@exec %sh&
  open="$kak_key"
  close="$kak_key"

  case "$kak_key" in
    ')') open='(' ;;
    ']') open='[' ;;
    '}') open='{' ;;
    '<gt>') open='<lt>' ;;
    '(') close=')' ;;
    '[') close=']' ;;
    '{') close='}' ;;
    '<lt>') close='<gt>' ;;
  esac

  echo "i$open<esc>a$close<esc>"
&@!

def delete-surround %!on-key %@exec %sh&
  echo "<a-a>${kak_key}s${kak_key}<ret>d"
&@!

map global user s ":surround<ret>"
map global user d ":delete-surround<ret>"
